### ISSUE TITLE
Tar archives do not work

### ISSUE THREAD

**Issue by JL2210** [vapier/chrome-ext-wicked-good-unarchiver#9] opened 2018-10-12 13:27 UTC
Tar archives do not work wih the latest version of Wicked Good Unarchiver. The tar archive simply shows up empty.

`uname -m`: `x86_64`
Version : `2017.12.0.77`
Installed from the Chrome Web Store.

**Comment by vapier** [comment] 2018-10-12 18:22
it's working fine for me.  if possible, please attach an example archive that is causing you problems.

**Comment by JL2210** [comment] 2018-10-12 19:28
I can send a link: https://github.com/stripedpajamas/vscodium/releases/download/1.28.1/VSCode-linux-arm64-1.28.1.tar.gz

**Comment by JL2210** [comment] 2018-10-12 19:34
![screenshot 2018-10-12 at 3 34 05 pm](https://user-images.githubusercontent.com/38843657/46890291-4f5e4700-ce34-11e8-971a-becc76376355.png)

**Comment by vapier** [comment] 2018-10-13 17:00
thanks for the example.  it seems to be related to the fact that the archive has `./` paths like in #7.  i'll prob have to update the code to filter that out better.

**Comment by vapier** [comment] 2018-10-13 17:01
simple archive to reproduce:
```
mkdir x
cd x
touch foo.txt
tar cf ../x.tar ./
```

that archive will have a `./` and `./foo.txt` entry.

**Comment by JL2210** [comment] 2018-10-13 22:55
Yeah. Same issue.

**Comment by JL2210** [comment] 2018-10-13 22:59
I'm not terribly good at c++, but if you don't have the time, I could write up a PR.

**Comment by JL2210** [comment] 2018-10-13 23:04
Also, a suggestion if you use the Chrome OS provided `tar` program: Use the `--strip-components=<num>` flag.

**Comment by vapier** [comment] 2018-10-14 01:52
the extension doesn't have access to any program like `tar`.  it wouldn't help though ... the tar format is very flexible which causes headaches here.  for example, it's valid to have:

* `./`
* `././`
* `./foo.txt`
* `blah.txt`
* `././blah.txt`

so if we used something like `--strip-components`, we'd rip out more than we should, and simultaneously less than we should :).

so we have to dynamically normalize every path in isolation.

**Comment by JL2210** [comment] 2018-10-14 02:45
`--xform s:'./'::`? I heard of a program called `pax` that may be useful.

**Comment by vapier** [comment] 2018-10-14 16:54
should be fixed in v2018.10.0.77 which i've released to the CWS now

see commit dc062a12f35881f93164368fa99dad1ce7e8034f for the details

**Closed as completed by vapier** 2018-10-14 16:54 UTC
Labels: bug

**Comment by JL2210** [comment] 2018-10-14 21:53
Great! Thank you for fixing this.
